### ISSUE TITLE
The name 'Bugfender' does not exist in the current context

### ISSUE THREAD

**Issue by francescotonini** [bugfender/bugfender-xamarin#1]
Hi, I am trying to run "XamarinSample" but I can't figure out how to fix this error:
`The name 'Bugfender' does not exist in the current context`

This error occurs at line 17 of SampleApplication.cs as well as in other pieces of code

**Comment by jgimenez** [comment]
Hi @francescotonini , as mentioned in the README, Xamarin Studio might highlight your code saying "The name Bugfender does not exist in the current context". This is a bug in the IDE, your code will compile fine.

**Comment by francescotonini** [comment]
I'm using Visual Studio and the app does not compile at all. Same issue occurs on Xamarin Studio. How can I compile an app if there are references missing?

[build output](https://github.com/bugfender/bugfender-xamarin/files/648992/build.output.txt)

**Comment by jgimenez** [comment]
This looks like a different issue, then. Reopening, will look into it.

**Comment by jgimenez** [comment]
It looks like this is a bug on the Android bindings generator. Depending on the Xamarin version it works or doesn't. I just wrote manually the Android interface so that the generator doesn't need to a2ed9dacb960f61a3fbc03713970e5c94463646b.
