### ISSUE TITLE
Bugfender does not compile with Xamarin.iOS 14.10

### ISSUE THREAD

**Issue by leobragatti** [bugfender/bugfender-xamarin#6]
Compiling an Xamarin.Forms project using Xamarin.iOS SDK 14.10 with Bugfender.SDK 2.0.3, I've got the following error:
```
Can't resolve the reference 'System.Void ObjCRuntime.ThrowHelper::ThrowArgumentNullException(System.String)', referenced from the method 'System.Void BugfenderSDK.Bugfender::ActivateLogger(System.String)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.
```

**Comment by Meekohi** [comment]
Same issue here.
`MTOUCH : error MT2101: Can't resolve the reference 'System.Void ObjCRuntime.ThrowHelper::ThrowArgumentNullException(System.String)', referenced from the method 'System.Void BugfenderSDK.Bugfender::ActivateLogger(System.String)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.`

**Comment by jgimenez** [comment]
Hi there, is that a beta version? According to this, iOS 14.10 is not listed as a release version:
https://docs.microsoft.com/en-us/xamarin/ios/release-notes/

This might be a bug within Xamarin.iOS. Have you tried upgrading to the latest version?

**Comment by petetataliba** [comment]
i am also have the issue
{System.MissingMethodException: Method not found: void ObjCRuntime.ThrowHelper.ThrowArgumentNullException(string)
  at Bugfender.Sdk.BugfenderBinding.ActivateLogger (System.String appToken, System.Boolean printToConsole) [0x00000] in /Users/gimix/git/bf/bugfender-xamarin/SDK/Bugfender.Sdk.iOS/BugfenderBinding.cs:17

**Comment by jgimenez** [comment]
This is likely an error in Xamarin 14.10. Thanks @petetataliba for your insights: updating to Xamarin 14.14 and rebuilding the solution solved the problem.
