### ISSUE TITLE
Use Bugfender in Xamarin shared project 

### ISSUE THREAD

**Issue by drowe5** [bugfender/bugfender-xamarin#9]
I can follow how to use Bugfender in iOS and Android project but how can I use it in the shared Xamarin Forms project.  The NuGet package will not add to the shared project because it says it is not supported.

**Comment by jgimenez** [comment]
Bugfender does not need to be in the Forms project, just install it in the iOS and Android projects. You can still use it from the Forms project without adding it, if you'd like to see how it's done you can check the Sample app in this project.

**Comment by drowe5** [comment]
I’ll take another look at the sample app but I didn’t see it on first pass.  How can I reference BugFender if it’s not included in the Forms project? I don’t  have any specific code in the iOS or Android apps so I really need to log everything from the Forms app.

**Comment by jgimenez** [comment]
You need to install Bugfender on the iOS and Android apps separately, but you can use Bugfender anywhere, something like

```C#
using Bugfender.Sdk;

BugfenderBinding bugfender = BugfenderBinding.Instance;
bugfender.DoSomething(...)
```
